# Generated by Django 5.2.2 on 2025-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='price_id',
            field=models.CharField(max_length=200),
        ),
    ]
